name: ci

on:
  push:
    paths-ignore:
      - '.gitignore'
      - 'LICENSE'
      - 'README.md'

jobs:
  validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Validate the Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3.4.2

  build:
    needs:
      - validation
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        java-version: [21]
    runs-on: ${{matrix.os}}-latest

    services:
      mysql:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{secrets.DATABASEPASSWORD}}
          MYSQL_DATABASE: kotlin_bank
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: adopt
      - name: Wait for MySQL
        run: |
          until mysql -h "127.0.0.1" -P "3306" -u "root" -e "SHOW DATABASES;" > /dev/null 2>&1; do
            echo "Waiting for MySQL to be available..."
            sleep 1
          done
      - name: build
        run: ./gradlew build -x test
      - name: test
        run: ./gradlew test --parallel || ./gradlew test --parallel || ./gradlew test --parallel